### ISSUE TITLE
mkdir?

### ISSUE THREAD

**Issue by alicebob** [drone-plugins/drone-sftp#6]
Would it be possible to run a mkdir on `destination_path` before uploading the files (if possible with recursive=true?). promise-sftp has `mkdir()` available.

**Comment by athieriot** [comment]
If ```promise-sftp``` support it I don't see any issue with that.
We might want to have it optional but if is useful for you it is a good idea.

I don't have much time at the moment though but if you fancy opening a Pull Request yourself we will be glad to review it.

I can point you into the right direction but the code base is quite small.

**Comment by athieriot** [comment]
Hi @alicebob,

Can I ask why you closed that issue?
Just as a matter of curiosity, if you don't need it any more of if you found an alternative.

Thanks

**Comment by alicebob** [comment]
Hi! Seems like I don't get around to making it, and we worked around it for now. No need to keep a ticket open forever, I thought.

**Comment by athieriot** [comment]
Ok :)
That's very up to you really.

Thanks for your answer

**Comment by thebwt** [comment]
Howdy!

I wouldn't mind taking a look at this, I personally would like it because I do destination_path: /some/path/$$BRANCH/$$BUILD_NUMBER. I'll start taking a look, let me know if you have any suggestions on where I should start.

**Comment by athieriot** [comment]
Hi @thebwt,

   You are perfectly right, it needs a new ```then``` at the line you specified.

   As ```promise-ftp``` returns a Promise, if you want to pass the ```file``` parameter on to the next Promise in the chain, you can probably do something like that:

      return sftp.mkdir(...).then(() => return file)

Please do try it before (Do not trust me ;))

Hope you'll manage. I am quite keen on accepting your work.
Also, if you want to go a little be further, I think it would be a good idea to make the creation of the destination directory an option (Ok to be true by default, but allowing to disable it)

**Comment by thebwt** [comment]
Hmm I don't think this is do-able with promise-sftp right now.

The way [promise-sftp's recursive](https://github.com/realtymaps/promise-sftp/blob/master/lib/promiseSftp.coffee#L327-L332)  mkdir correlates to promise-ftp's mkdir method is logically incompatible. Specifically it needs to pass a second a parameter of the boolean type, but promise-sftp will only pass on an object type.

I may just look to use rsync for this instead, but will try to get changes into promise-sftp.

**Comment by athieriot** [comment]
Hi there,

I am not quite sure why they did it like that but it's genuine (Odd probably but seems legit anyway :p)

What seems to happen is that you have the possibility to call ```mkdir``` with only two arguments: the ```dirPath``` and the ```attributes```. In that scenario, they consider that you do not want to recursively create the directories and call the mkdir method only once.

If you pass three arguments, the ```dirPath```, a Boolean for ```recursive``` and the ```attributes```, the code seem to loop over all the part of the path and call ```mkdir``` for each of these, manually.

It looks odd (where they could probably have check the arity) but I would invite you to try the code as it is, trusting the library and see how it goes :)

Thank you so much for your help

Aurélien

**Comment by thebwt** [comment]
So it looks like the whole function is actually broken when you do recursive stuff. I've opened a pr to try and get it fixed (there aren't issues on that repo)

You were totally right, that it could be called fine. The problem is that it's looping mechanism piles a bunch of async tasks to run off the variable currPath. and currPath is the final folder by the time it can run those tasks, thus it will always fail.

[PR](https://github.com/realtymaps/promise-sftp/pull/4)

**Comment by athieriot** [comment]
If you want to try to fix ```promise-sftp```, you can experiment a little by modifying the file directly in your node_module/ at first and see how you can sort things out. (And when you happy, fork the repo and apply your fix)

I think you identified the problem correctly and I don't think it's going to be to hard to solve.

As the problem is that ```currPath``` will hold the full path at the time of execution, you could create a local, temporary variable in the ```then()``` section line 345-346 containing the actual current path at the moment of creation.

Something like:

      tempPath = currPath
      @mkdir(tempPath, false, attributes)

Don't trust me and check though ;)

Tell me off if you know those things already but there is two interesting help page that you can read in order to understand the problem a bit more:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures (And particularly "Creating closures in loops: A common mistake")

- http://coffeescript.org/ (And particularly "Lexical Scoping and Variable Safety")

Understanding variable scope is the most important knowledge you can have in Javascript.

**Comment by thebwt** [comment]
Fix submitted in that PR. Assuming that gets accepted/adapted in, I suppose we can just add a then block to the plugin that says "if this flag, return sftp.mkdir; else return null" I'll do some local testing using the patched library.

**Comment by athieriot** [comment]
I hope that PR will be accepted. 
You are doing a great job.

**Comment by thebwt** [comment]
Alright, the PR is accepted, and new release out. Thanks for pushing me outside my comfort zone!
